tickeet/config/routes.rb
Rails.application.routes.draw do
   root "projects#index"

   resources :projects #RESTful [index,show,new,create, update, destroy ]routes ti the seven actions
end

tickeet/app/models/project.rb
class Project < ActiveRecord::Base
	 validates :name, presence: true
end

tickeet/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

tickeet/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

   before_action :set_project, only: [:show, 
                                      :edit, 
                                      :update, 
                                      :destroy]
                                     
      def index
      	 @projects = Project.all
      end

      def new
      	  @project = Project.new
      end

      def create
           @project = Project.new(project_params)

             if @project.save
             	flash[:notice] = "Project has been created."
             	redirect_to @project
             else
             	flash[:alert] = "Project has not been created."
             	render "new"
             end
      end

      def show
          
      end

      def edit
         
      end

      def update

        if @project.update(project_params)
          flash[:notice] = "Project has been updated."
          redirect_to @project
        else
          flash[:alert] = "Project has not been updated."
          render "edit"
        end

      end

        def destroy
           
           @project.destroy

            flash[:notice] = "Project has been destroyed."

            redirect_to projects_path
        end

   private

   def project_params
       params.require(:project).permit(:name, :description)
   end

   private

  def set_project
     @project = Project.find(params[:id])

   rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The project you were looking" +
                      " for could not be found."
      redirect_to projects_path
    end

end

tickeet/app/helpers/application_helper.rb
module ApplicationHelper
	def title(*parts)
		unless parts.empty?
			content_for :title do
				(parts << "Ticketee").join(" - ")
			end
		end
	end
end

tickeet/app/helpers/projects_helper.rb
module ProjectsHelper
end

tickeet/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>
	<% if content_for?(:title) %>
		<%= yield(:title) %>
	<% else %>
		Ticketee
	<% end %>
</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= flash.each do |key, value| %>

<div class='flash' id='<%= key %>'>
    <%= value %>
</div>
<% end %>

</body>
</html>

tickeet/app/views/projects/_form.html.erb
 <% if @project.errors.any? %>

   <div id="error_explanation">
       <h2><%= pluralize(@project.errors.count, "error") %>
         prohibited this project from being saved:
       </h2>
 
    <ul>
    	 <% @project.errors.full_messages.each do |msg| %>
    	  <li><%= msg %></li>
    	 <% end %>
    </ul>


   </div>

 <% end %>

<%= form_for(@project) do |f| %>

  <p>
  	  <%= f.label :name %><br />
  	  <%= f.text_field :name %>
  </p>

  <p>
  	 <%= f.label :description %><br />
  	 <%= f.text_field :description %>
  </p>
  <%= f.submit %>

<% end %>

tickeet/app/views/projects/edit.html.erb
<h2>Edit project</h2>

<%= render "form" %>

tickeet/app/views/projects/index.html.erb
<h2>Projects</h2>
<ul>
	<% @projects.each do |project| %>
       <li>
       	   <%= link_to project.name, project %>
       </li>
	<% end %>
</ul>
<%= link_to "New Project", new_project_path %>

tickeet/app/views/projects/new.html.erb
<h2>New Project</h2>
<%= render "form" %>

tickeet/app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<%= link_to "Edit Project", edit_project_path(@project) %>
<%= link_to "Delete Project",
    project_path(@project),
    method: :delete,
    data: { confirm: 
    	      "Are you sure you want to delete this project?"
          } %>